//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateBannerClick
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ClickDate { get; set; }
        public Nullable<int> BannerID { get; set; }
        public Nullable<int> AffiliateID { get; set; }
        public string UrlReferrer { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
        public virtual AffiliateBanner AffiliateBanner { get; set; }
    }
}
