//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateSummaryPerSite
    {
        public int ID { get; set; }
        public Nullable<int> BannerID { get; set; }
        public Nullable<int> Impressions { get; set; }
        public Nullable<int> Clicks { get; set; }
        public Nullable<int> Lead { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<System.DateTime> SummaryDate { get; set; }
        public Nullable<int> AffiliateID { get; set; }
        public string Product { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
    }
}
