//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateRevenueReport
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AffiliateDate { get; set; }
        public Nullable<int> Visits { get; set; }
        public Nullable<int> Registrations { get; set; }
        public Nullable<int> Deposits { get; set; }
        public Nullable<decimal> DepositSum { get; set; }
        public Nullable<decimal> TurnOver { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<int> Players { get; set; }
        public Nullable<int> AffiliateID { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
    }
}
