//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AffiliateDBEntities : DbContext
    {
        public AffiliateDBEntities()
            : base("name=AffiliateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AffilateRequestWithdraw> AffilateRequestWithdraws { get; set; }
        public virtual DbSet<Affiliate> Affiliates { get; set; }
        public virtual DbSet<AffiliateAccount> AffiliateAccounts { get; set; }
        public virtual DbSet<AffiliateBankAccount> AffiliateBankAccounts { get; set; }
        public virtual DbSet<AffiliateBanner> AffiliateBanners { get; set; }
        public virtual DbSet<AffiliateBannerClick> AffiliateBannerClicks { get; set; }
        public virtual DbSet<AffiliateBannerSize> AffiliateBannerSizes { get; set; }
        public virtual DbSet<AffiliateBannerView> AffiliateBannerViews { get; set; }
        public virtual DbSet<AffiliateMedia> AffiliateMedias { get; set; }
        public virtual DbSet<AffiliatePixel> AffiliatePixels { get; set; }
        public virtual DbSet<AffiliateRequestWithdrawl> AffiliateRequestWithdrawls { get; set; }
        public virtual DbSet<AffiliateRevenueReport> AffiliateRevenueReports { get; set; }
        public virtual DbSet<AffiliatesBanner> AffiliatesBanners { get; set; }
        public virtual DbSet<AffiliatesCommission> AffiliatesCommissions { get; set; }
        public virtual DbSet<AffiliateSummaryPerSite> AffiliateSummaryPerSites { get; set; }
        public virtual DbSet<AffiliateTicket> AffiliateTickets { get; set; }
        public virtual DbSet<AffiliateTicketContent> AffiliateTicketContents { get; set; }
        public virtual DbSet<AffiliateWithdrawlHistory> AffiliateWithdrawlHistories { get; set; }
        public virtual DbSet<SubAffiliate> SubAffiliates { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
