//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateWithdrawlHistory
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountPayout { get; set; }
        public Nullable<decimal> BalanceAfterPayout { get; set; }
        public string Status { get; set; }
    }
}
