//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateBanner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AffiliateBanner()
        {
            this.AffiliatesBanners = new HashSet<AffiliatesBanner>();
        }
    
        public int ID { get; set; }
        public string BannerName { get; set; }
        public string BannerPath { get; set; }
        public string Javascript { get; set; }
        public string DirectLink { get; set; }
        public string Htmlcode { get; set; }
        public string BannerType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> BannerSizeID { get; set; }
    
        public virtual AffiliateBannerSize AffiliateBannerSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliatesBanner> AffiliatesBanners { get; set; }
    }
}
