//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateTicketContent
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public string Subject { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActivateOnCreation { get; set; }
        public Nullable<bool> IsPopupUntilApproval { get; set; }
        public Nullable<bool> IsSendByEmail { get; set; }
        public Nullable<bool> IsReadByAffiliate { get; set; }
        public Nullable<int> TicketID { get; set; }
    
        public virtual AffiliateTicket AffiliateTicket { get; set; }
    }
}
