//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliatePixel
    {
        public int ID { get; set; }
        public string Pixel { get; set; }
        public string PixelTrigger { get; set; }
        public string Code { get; set; }
    }
}
