//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affiliate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Affiliate()
        {
            this.AffiliateBannerClicks = new HashSet<AffiliateBannerClick>();
            this.AffiliateBannerViews = new HashSet<AffiliateBannerView>();
            this.AffiliateMedias = new HashSet<AffiliateMedia>();
            this.AffiliateRequestWithdrawls = new HashSet<AffiliateRequestWithdrawl>();
            this.AffiliateRevenueReports = new HashSet<AffiliateRevenueReport>();
            this.AffiliatesBanners = new HashSet<AffiliatesBanner>();
            this.AffiliatesCommissions = new HashSet<AffiliatesCommission>();
            this.AffiliateSummaryPerSites = new HashSet<AffiliateSummaryPerSite>();
            this.AffiliateTickets = new HashSet<AffiliateTicket>();
            this.SubAffiliates = new HashSet<SubAffiliate>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<int> AffiliateUserID { get; set; }
        public string Tile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string AffiliateLink { get; set; }
        public Nullable<System.DateTime> AffiliateLastLogin { get; set; }
        public Nullable<System.DateTime> LastActivityTime { get; set; }
        public string Skype { get; set; }
        public Nullable<int> AccountID { get; set; }
    
        public virtual AffiliateBankAccount AffiliateBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateBannerClick> AffiliateBannerClicks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateBannerView> AffiliateBannerViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateMedia> AffiliateMedias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateRequestWithdrawl> AffiliateRequestWithdrawls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateRevenueReport> AffiliateRevenueReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliatesBanner> AffiliatesBanners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliatesCommission> AffiliatesCommissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateSummaryPerSite> AffiliateSummaryPerSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateTicket> AffiliateTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubAffiliate> SubAffiliates { get; set; }
    }
}
