//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateBankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AffiliateBankAccount()
        {
            this.Affiliates = new HashSet<Affiliate>();
        }
    
        public int ID { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string BankBranch { get; set; }
        public string BankEmail { get; set; }
        public string IBAN { get; set; }
        public string Swift { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string ComissionPlan { get; set; }
        public string MinimalPayout { get; set; }
        public string PayoutCurrency { get; set; }
        public string NetlleterEmail { get; set; }
        public string SkrillEmail { get; set; }
        public string PaymentType { get; set; }
        public string CompanyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affiliate> Affiliates { get; set; }
    }
}
