//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affiliate_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateBannerSize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AffiliateBannerSize()
        {
            this.AffiliateBanners = new HashSet<AffiliateBanner>();
        }
    
        public int ID { get; set; }
        public string BannerName { get; set; }
        public string BannerPath { get; set; }
        public string Javascript { get; set; }
        public string HTMLCode { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string DirectLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateBanner> AffiliateBanners { get; set; }
    }
}
